import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./provider";
import { AppBarClient } from "./components/AppBarClient";
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Toaster position="bottom-right"/>
          <AppBarClient />
            <div className={inter.className}>{children}</div>
        </Provider>
 
        </body>
    </html>
  );
}
